In [3]:
import numpy as np


In [35]:
a=np.array([[1,2,3],[4,5,6]])
a.shape
a

array([[1, 2, 3],
       [4, 5, 6]])

创建随机数组

In [10]:
random_array=np.random.rand(3,3)
random_array

array([[0.78098411, 0.28376005, 0.16224387],
       [0.89372371, 0.63020874, 0.66666255],
       [0.42315765, 0.71244233, 0.26449589]])

数组排序

In [33]:
sorted_array_row=np.sort(random_array)
sorted_array_row


array([[0.16224387, 0.28376005, 0.78098411],
       [0.63020874, 0.66666255, 0.89372371],
       [0.26449589, 0.42315765, 0.71244233]])

In [23]:
sorted_array_column=np.sort(random_array,axis=0)
sorted_array_column

array([[0.42315765, 0.28376005, 0.16224387],
       [0.78098411, 0.63020874, 0.26449589],
       [0.89372371, 0.71244233, 0.66666255]])

数组分割

In [29]:
np.array_split(sorted_array_column,3,axis=1)

[array([[0.42315765],
        [0.78098411],
        [0.89372371]]),
 array([[0.28376005],
        [0.63020874],
        [0.71244233]]),
 array([[0.16224387],
        [0.26449589],
        [0.66666255]])]

In [30]:
np.array_split(sorted_array_column,2,axis=1)

[array([[0.42315765, 0.28376005],
        [0.78098411, 0.63020874],
        [0.89372371, 0.71244233]]),
 array([[0.16224387],
        [0.26449589],
        [0.66666255]])]

In [40]:
# 创建一个 3x2 的矩阵
data = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

# 增加一列
new_column = np.array([7, 8, 9])
data_with_new_column = np.append(data, new_column.reshape(-1, 1), axis=1)
data_with_new_column

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

逆矩阵

In [44]:
# 定义一个矩阵
A = np.array([[1, 2],
              [3, 4]])

# 计算逆矩阵
A_inv = np.linalg.inv(A)

print("矩阵 A:\n", A)
print("逆矩阵 A_inv:\n", A_inv)

矩阵 A:
 [[1 2]
 [3 4]]
逆矩阵 A_inv:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [45]:
data_inv=np.linalg.inv(data_with_new_column)
print("矩阵:\n",data_with_new_column)
print("逆矩阵:\n",data_inv)

矩阵:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]
逆矩阵:
 [[-1.12589991e+15  2.25179981e+15 -1.12589991e+15]
 [ 1.21972490e+15 -2.43944980e+15  1.21972490e+15]
 [-1.87649984e+14  3.75299969e+14 -1.87649984e+14]]


计算矩阵行列式

In [46]:
# 定义一个矩阵
A = np.array([[1, 2],
              [3, 4]])

# 计算行列式
det_A = np.linalg.det(A)
print("行列式 det(A):", det_A)

# 如果行列式不为 0，计算逆矩阵
if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("逆矩阵 A_inv:\n", A_inv)

    # 验证逆矩阵的正确性：A * A_inv 应该接近单位矩阵
    identity_matrix = np.dot(A, A_inv)
    print("验证 A * A_inv:\n", identity_matrix)
else:
    print("矩阵 A 是奇异的，无法计算逆矩阵。")

行列式 det(A): -2.0000000000000004
逆矩阵 A_inv:
 [[-2.   1. ]
 [ 1.5 -0.5]]
验证 A * A_inv:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [53]:
array_a=np.zeros((3,3))
array_a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
array_b=np.random.randint(1,100,(4,5))
array_b 

array([[35, 85, 27, 13, 47],
       [38, 96, 43, 59, 61],
       [34,  2,  8, 18, 92],
       [52, 24, 21, 93, 26]])

In [65]:
arr = np.array([1, 2, 3, 4, 5])
arr*10
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a_b=np.dot(a,b)
a_b

np.int64(32)

In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[:, 0:2]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [78]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [84]:
arr = np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
arr = np.array([[1, 2], [3, 4]])
arr.flatten()

array([1, 2, 3, 4])

In [93]:
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
median=np.median(arr)
std = np.std(arr)
print("mean=",mean,"\n","median=",median,"\n","std=",std)

mean= 3.0 
 median= 3.0 
 std= 1.4142135623730951


In [96]:
arr = np.array([[1, 2], [3, 4]])
min = np.min(arr)
max=np.max(arr)
print(min,max)

1 4


In [102]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = arr[arr > 3]
newarr

array([4, 5, 6])

Replace all elements less than 5 with 0 in the array arr = np.array([[1, 2, 3], [4, 5, 6]]).


In [103]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[arr<5]=0 
# arr = np.where(arr < 5, 0, arr)
arr

array([[0, 0, 0],
       [0, 5, 6]])

Concatenate two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.


In [109]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
arr = np.arange(10)
np.array_split(arr,3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Compute the determinant of the matrix A = np.array([[1, 2], [3, 4]]).


In [111]:
A = np.array([[1, 2], [3, 4]])
det_A=np.linalg.det(A)
det_A

np.float64(-2.0000000000000004)

Compute the eigenvalues and eigenvectors of the matrix A = np.array([[1, 2], [2, 1]]).


Add the array a = np.array([1, 2, 3]) to each row of the array b = np.array([[4, 5, 6], [7, 8, 9]]).

In [114]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
b+a

array([[ 5,  7,  9],
       [ 8, 10, 12]])

Multiply the array a = np.array([1, 2, 3]) with each column of the array b = np.array([[4, 5], [6, 7], [8, 9]]).

In [123]:
a = np.array([1, 2, 3])
b = np.array([[4, 5], [6, 7], [8, 9]])
a=np.reshape(a,(3,-1))
a*b
# result = a[:, np.newaxis] * b
# result

array([[ 4,  5],
       [12, 14],
       [24, 27]])

Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), extract the elements at positions (0, 1), (1, 2), and (2, 0).
Replace the diagonal elements of the array arr with 0.


In [130]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
extracted_elements = arr[[0, 1, 2], [1, 2, 0]]
np.fill_diagonal(arr, 0)
extracted_elements
arr

array([[0, 2, 3],
       [4, 0, 6],
       [7, 8, 0]])

Solve the System of Linear Equations
Equations:
2x+3y=5
4x+5y=7

In [131]:
# Coefficients matrix
coeff_matrix = np.array([[2, 3],
                         [4, 5]])

# Constants vector
const_vector = np.array([5, 7])

# Solve the system
solution = np.linalg.solve(coeff_matrix, const_vector)
print("Solution for x and y:", solution)

Solution for x and y: [-2.  3.]


In [132]:
# Define array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Shuffle the rows
np.random.shuffle(arr)
print("Shuffled Array:\n", arr)

Shuffled Array:
 [[1 2 3]
 [7 8 9]
 [4 5 6]]


In [133]:
# Array to save
arr_to_save = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Save array to file
np.savetxt("array.txt", arr_to_save)

# Load array from file
loaded_array = np.loadtxt("array.txt")
print("Loaded Array:\n", loaded_array)

Loaded Array:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [134]:
def normalize_array(arr):
    # Subtract mean and divide by standard deviation for each column
    mean = np.mean(arr, axis=0)
    std_dev = np.std(arr, axis=0)
    return (arr - mean) / std_dev

# Example usage
arr_to_normalize = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
normalized_arr = normalize_array(arr_to_normalize)
print("Normalized Array:\n", normalized_arr)

Normalized Array:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


Euclidean Distance Between Two Vectors

In [135]:
def euclidean_distance(vec1, vec2):
    # Compute Euclidean distance
    return np.linalg.norm(vec1 - vec2)

# Example usage
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("Euclidean Distance:", euclidean_distance(v1, v2))

Euclidean Distance: 5.196152422706632


In [141]:
import time
# Generate a large 1000x1000 array with random values
arr = np.random.rand(1000, 1000)

# 1. Sum using a Python loop
start_time_loop = time.time()
sum_loop = 0
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        sum_loop += arr[i, j]
end_time_loop = time.time()

# 2. Sum using NumPy's np.sum()
start_time_np = time.time()
sum_np = np.sum(arr)
end_time_np = time.time()

# Print the results
print(f"Sum using Python loop: {sum_loop}")
print(f"Time taken by Python loop: {end_time_loop - start_time_loop:.5f} seconds")

print(f"\nSum using np.sum(): {sum_np}")
print(f"Time taken by np.sum(): {end_time_np - start_time_np:.5f} seconds")

# Check if both sums are equal
if np.isclose(sum_loop, sum_np):
    print("\nBoth sums are approximately equal.")
else:
    print("\nSums do not match!")

Sum using Python loop: 500245.3228933129
Time taken by Python loop: 0.17285 seconds

Sum using np.sum(): 500245.3228933173
Time taken by np.sum(): 0.00040 seconds

Both sums are approximately equal.
